### ISSUE TITLE
NPE While Using Library

### ISSUE THREAD

**Issue by ECD00UFA** [Yalantis/Context-Menu.Android#45]
Following is the Bug Report I got today : 

Caused by: java.lang.NullPointerException
at android.os.Parcel.readTypedList(Parcel.java:1749)
at com.yalantis.contextmenu.lib.MenuParams.<init>(MenuParams.java:109)
at com.yalantis.contextmenu.lib.MenuParams.<init>(MenuParams.java:11)
at com.yalantis.contextmenu.lib.MenuParams$1.createFromParcel(MenuParams.java:119)
at com.yalantis.contextmenu.lib.MenuParams$1.createFromParcel(MenuParams.java:117)
at android.os.Parcel.readParcelable(Parcel.java:2103)
at android.os.Parcel.readValue(Parcel.java:1965)

Any Help????

**Comment by TeeRawk** [comment]
Hello,thanks for the report, can you  explai steps how you got this npe ?
