### ISSUE TITLE
Vector Drawable as Menu icon

### ISSUE THREAD

**Issue by pooyanmajd** [Yalantis/Context-Menu.Android#54]
It doesn't show vector drawable as menu icon on API 19 with below err:

```
   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                                                                        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
                                                                        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877) 
```

**Comment by warko-san** [comment]
Hi, @pooyanmajd! Currently this lib doesn't support vector-drawables. Can you use just ordinary drawable?

**Comment by pooyanmajd** [comment]
Hi @warko-san, I fixed the issue by adding this support for vector-drawable
`AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);`
